# extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*
  - packages/**/node_modules/**/*
  - build/**/*
plugins:
  - stylelint-selector-bem-pattern
  - stylelint-scss
  - stylelint-order
rules:
#   # Follow best practices
#   font-family-name-quotes: always-where-recommended
#   # http://stackoverflow.com/questions/2168855/is-quoting-the-value-of-url-really-necessary
#   function-url-quotes: never
#   # https://www.w3.org/TR/selectors/#attribute-selectors
#   # http://stackoverflow.com/q/3851091
#   selector-attribute-quotes: always
#   # Double-quotes are our convention throughout our codebase within (S)CSS. They also reflect how
#   # attribute strings are normally quoted within the DOM.
#   string-quotes: double
#   # https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/smacss.yml
  order/declaration-block-properties-specified-order:
    - display
    - position
    - top
    - right
    - bottom
    - left

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - float
    - clear

    - columns
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-count
    - column-width

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    # Border

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    # Text

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Other

    - border-collapse
    - border-spacing
    - box-shadow
    - caption-side
    - content
    - cursor
    - empty-cells
    - opacity
    - overflow
    - quotes
    - speak
    - table-layout
    - vertical-align
    - visibility
    - z-index
  declaration-property-unit-whitelist:
    font-size:
      - "rem"
      - "px"
